### ISSUE TITLE
Provider Cloudinary

### ISSUE THREAD

**Issue by edymatimbe** [john-smilga/strapi-latest-store-api#1]
I'm tired now after see some f your videos (overload) but that cloudinary is making me flip over upside down! In my Strapi plugins the file upload don't show up!

**Comment by john-smilga** [comment]
Strapi changed it's setup - you don't have to update setting UI (like I do in video), once you add your credentials, it's automatically added.

**Comment by edymatimbe** [comment]
Let me try with that tip! But please do a video with an update to that topic showing how to do it now! Best Wishes Le Mer 3 Juin 2020 2:15, john-smilga <notifications@github.com> a écrit :Strapi changed it's setup - you don't have to update setting UI (like I do in video), once you add your credentials, it's automatically added.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
